type Book {
    id:Int
    title: String
    author: String
  }

# type Query {
#     books: [Book]
#   }
type Roles{
  id:Int
  role:String
}
  type Mutation{
    createBook(title:String,author:String,id:Int):Book
  }
